language: cpp
cache: ccache
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
git:
    depth: 2
before_install: ./install_dependencies.sh
script: ./fetch_umbrella_build_and_test.sh