# This is used to verify that the documentation compiles.
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -q Sphinx==1.1.3 --use-mirrors"
# command to run tests
script: cd docs && sphinx-build -nW -b html -d _build/doctrees . _build/html
# Flags used here, not in `make html`:
#  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
#  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
